title: The Machine Vernacular
description: A dictionary of emergent machine usage
url: "https://www.themachinevernacular.net"
baseurl: ""
markdown: kramdown

collections:
  entries:
    output: false

exclude:
  - plugins/
  - docs/
  - scripts/
  - README.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - vendor/
